import "./globals.css";

export const metadata = {
  title: "Bernhard Ricardo Putranto",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" href="wave.svg"></link>
      <body>{children}</body>
    </html>
  );
}
